/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Suhail;

public class App {
    
    public static void main(String[] args) {
        int STnumber = 10455559;
        String Name = "Suhail";
        String Surname = "Allie";
        String Email = "ST10455559@rcconnect.edu.za";
        double PhoneNumber = 745275726;
        int Test1 = 90;
        int Test2 = 80;
        int Assignment = 70;
        int ExamMark = 85;
        double DpMark;
        double FinalMark;
        
        DpMark = (Test1 + Test2 + Assignment)/3;
        FinalMark = (DpMark * 0.4) + (ExamMark * 0.6);
        
        System.out.println("Dp Mark - " + DpMark);
        System.out.println("Final Mark - " + FinalMark);
        System.out.println("Exam mark - " + ExamMark);
       
        System.out.println("STnumber - " + STnumber);
        System.out.println("Name - " + Name);
        System.out.println("Surname - " + Surname);
        System.out.println("Email - " + Email);
        System.out.println("PhoneNumber - " + PhoneNumber);
        System.out.println("Test1 - " + Test1);
        System.out.println("Test2 - " + Test2);
        System.out.println("Assignment - " + Assignment);
        
        
              
    }

    
    }

